services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__Database=Server=database;Port=5432;Database=taskmanager;User Id=postgres;Password=root;Timeout=15
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "1234:8080"
  
  database:
    image: postgres:16.3-alpine3.18
    restart: always
    environment:
      POSTGRES_DB: taskmanager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    expose:
      - "5432"
    volumes:
      - "db-vol:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  db-vol:
