services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__Database=Server=database;Port=5432;Database=taskmanager;User Id=root;Password=root;Timeout=15
    depends_on:
      - database
    ports:
      - "1234:8080"
  
  database:
    image: postgres:16.3-alpine3.18
    restart: always
    environment:
      POSTGRES_DB: taskmanager
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    expose:
      - "5432"
    volumes:
      - "db-vol:/var/lib/postgresql/data"
volumes:
  db-vol:
